
##full list of regions, can produce EU-14 map
select_nuts <- gisco_get_nuts(nuts_id = c("AT11","AT21","AT12","AT13","AT32","AT22","AT33","AT31","AT34","BE21","BE10","BE24","BE31","BE5","BE23","BE32","BE33","BE22","BE34","BE35","DK01","DK02","DK03","DK04","DK05","FI19","FI1B","FI1C","FI1D","FI20","FR10","FRB0","FRC1","FRC2","FRD1","FRD2","FRE1","FRE2","FRF1","FRF2","FRF3","FRG0","FRH0","FRI1","FRI2","FRI3","FRJ1","FRJ2","FRK1","FRK2","FRL0","FRM0","DE11","DE12","DE13","DE14","DE21","DE22","DE23","DE24","DE25","DE26","DE27","DE30","DE40","DE50","DE60","DE71","DE72","DE73","DE80","DE91","DE92","DE93","DE94","DEA1","DEA2","DEA3","DEA4","DEA5","DEB1","DEB2","DEB3","DEC0","DED2","DED4","DED5","DEE0","DEF0","DEG0","ITC1","ITC2","ITC3","ITC4","ITH1","ITH2","ITH3","ITH4","ITH5","ITI1","ITI2","ITI3","ITI4","ITF1","ITF2","ITF3","ITF4","ITF5","ITF6","ITG1","ITG2","NL11","NL12","NL13","NL21","NL22","NL31","NL32","NL33","NL34","NL41","NL42","NL23","NO01","NO02","NO03","NO04","NO05","NO06","NO07","PT11","PT15","PT16","PT17","PT18","ES61","ES24","ES12","ES53","ES70","ES13","ES42","ES41","ES51","ES52","ES43","ES11","ES30","ES62","ES22","ES21","ES23","SE11","SE12","SE21","SE22","SE23","SE31","SE32","SE33","CH01","CH02","CH03","CH04","CH05","CH06","CH07","LU00"))

##packages
library(tidyverse)
library(sf)
library(dplyr)


##set the data frame
df# <- read.csv("E:/New Desktop/map_data.csv", sep=";")

##match the dataset to the EU nuts2 geo-dataset
region_filter <- EU_nuts2 %>% 
          left_join(df2, by = c("NUTS_ID" = "NUTS_ID"))
##clean
region_filtered <- region_filter %>% drop_na()

## correspondence: 1=1900-1915
##                 2=1925-1938
##                 3=1980-2000
##                 4=2000-2015

##plot
ggplot(region_filtered) + geom_sf(aes(fill = Club_Membership)) +         scale_fill_gradient2(
     low = "red", 
     mid = "white", 
     high = "blue", 
     midpoint = 1) + labs(title = "Convergence Clubs for 1900-1910", subtitle = "EU NUTS-2 regions", caption = "Author's own drawing.")


## Remove Hawaii, Alaska, and Puerto Rico to just focus on the rest states
  filter(!name %in% c("Hawaii", "Alaska", "Puerto Rico"))


##comparison 

##first-30 regions
df.first30 <- read.csv("E:/New Desktop/first_30_compare.csv", sep=";")

region_filter.first30 <- EU_nuts2 %>% 
     left_join(df.first30, by = c("NUTS_ID" = "NUTS_ID"))

region_filtered.first30 <- region_filter.first30 %>% drop_na()

ggplot(region_filtered.first30) + geom_sf(aes(fill = Club_Membership)) +         scale_fill_manual(values = c("red", "lightgray", "yellow", "orange")) + labs(title = "Winning 30 regions comparison for pre-war and post-2000", subtitle = "EU NUTS-2 regions", caption = "Author's own drawing.")


##last-40
df.last30 <- read.csv("E:/New Desktop/last_30_compare.csv", sep=";")
 
region_filter.last30 <- EU_nuts2 %>% 
     left_join(df.last30, by = c("NUTS_ID" = "NUTS_ID"))

region_filtered.last30 <- region_filter.last30 %>% drop_na()

ggplot(region_filtered.last30) + geom_sf(aes(fill = Club_Membership)) +         scale_fill_manual(values = c("red", "lightgray", "yellow", "orange")) + labs(title = "Lagging 40 regions comparison for pre-war and post-2000", subtitle = "EU NUTS-2 regions", caption = "Author's own drawing.")

-----------------------------------------------------------------
##alternative mapping

library("tmap")

tm_shape(mregion_filtered5) + tm_polygons(style="quantile", col = "Club_Membership") + tm_legend(outside = TRUE, text.size = .8)

##plot different attributes of shapefile
plot(mregion_filtered1_dropped['Region']) # plot one of the attributes

##adding breaks to club_membership: jenks or manual
plot(mregion_filtered4['Club_Membership'],breaks = "jenks")
plot(mregion_filtered5['Club_Membership'],breaks = c(1,3,6,9))



